name = "NipponColors"
uuid = "6ad8dad8-821c-43d6-81bb-8d3dfb5c0fb6"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
Colors = "0.12"
PyCall = "^1"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
